### PR TITLE
Fix TLS config for SASL

### LINKED ISSUE #26: Conversion to SARAMA does not support SASL
during the conversion to sarama the TLSConfig logic was dropped for SASL

Old code connector.go L153
```Go
	if conn.config.SASL.User == "" {
		tlsC, err = conn.config.TLS.MakeTLSConfig()
	} else {
		conn.dialer.SASLMechanism = plain.Mechanism{
			Username: conn.config.SASL.User,
			Password: conn.config.SASL.Password,
		}
		if conn.config.SASL.InsecureSkipVerify {
			tlsC = &tls.Config{
				InsecureSkipVerify: conn.config.SASL.InsecureSkipVerify,
			}
		}
	}
```
Now consumer, manager, and producer do not create the correct TLS Config needed for SASL
```Go
	if cc.SASL.User != "" {
		sc.Net.SASL.Enable = true
		sc.Net.SASL.User = cc.SASL.User
		sc.Net.SASL.Password = cc.SASL.Password
	} else if tlsC, err := cc.TLS.MakeTLSConfig(); err == nil {
		sc.Net.TLS.Enable = (tlsC != nil)
		sc.Net.TLS.Config = tlsC
	}
```

### PR DESCRIPTION
**Pull request by variadico**
Currently, we don't honor the InsecureSkipVerify parameter. This causes
connection problems when connecting to Azure.

This change adds TLS config for InsecureSkipVerify when using SASL.

Resolves #26

### CODE REVIEW

**Comment by variadico** [comment]
I tested on Azure with this config.

```
connect: [
  {
    id: "test"
    type: "NATSToKafka"

    subject: "test"

    brokers: ["test.servicebus.windows.net:9093"]
    topic: "test"
    sasl: {
      user: "$ConnectionString"
      password: "Endpoint=testtesttest"
      insecureskipverify: true
    }
  }
]
```
`nats-kafka -c my.conf`

Everything seemed to work now. I also verified that it didn't work before.

**Review by wallyqs — APPROVED** [review]
LGTM

File: server/kafka/manager.go [hunk 1]
```diff
@@ -39,8 +40,16 @@ func NewManager(cc conf.ConnectorConfig, bc conf.NATSKafkaBridgeConfig) (Manager
 
 	if cc.SASL.User != "" {
 		sc.Net.SASL.Enable = true
+		sc.Net.SASL.Mechanism = sarama.SASLTypePlaintext
 		sc.Net.SASL.User = cc.SASL.User
 		sc.Net.SASL.Password = cc.SASL.Password
```
Comment (wallyqs) [inline server/kafka/manager.go:45]: `sc.Net.SASL.Handshake` not needed?

Comment (variadico) [reply server/kafka/manager.go:45]: It defaults to `true`.
https://pkg.go.dev/github.com/Shopify/sarama#Config

But we could add it to make sure it doesn't change beneath our feet.

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by ColinSullivan1 — APPROVED** [review]
LGTM.
